### ISSUE TITLE
Connector type and placement

### ISSUE THREAD

**Issue by Qwerty-OFF** [rusefi/proteus-Honda-K-125-adapter#1]
To determine the outline of the board, we need to select vertical or horizontal connectors and decide how to place them on the board

horizontal
![image](https://user-images.githubusercontent.com/4116383/134263678-e4ab1bb6-dc9d-4028-9f83-957624626cbf.png)

vertical
![image](https://user-images.githubusercontent.com/4116383/134263708-fc7d5631-4058-4cf7-9f82-31ac3ae04cfa.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/134264684-33bb7469-1ce1-44e3-9d68-4f0432ff1cc6.png)

![image](https://user-images.githubusercontent.com/48498823/134264756-3675c904-015f-4998-aa26-2c268a069c78.png)

**Comment by rusefillc** [comment]
horizontal option it totally unrealistic
vertical option maaaaaaaybe

it really starts to look like we will have to solder wires. let's go with vertical even while in reality we are probably soldering wires


Also let's just go with "normal" connector matching proteus, pin 1 of proteus going to pin 1 on the board. The wires would have to twist and we will just live with that for now.
