### ISSUE TITLE
23 pin proteus pin

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-K-125-adapter#11]
pins 21 and 22 are NOT CAN see https://rusefi.com/docs/pinouts/proteus/

there is also confusion between older 23 pinout (some residual mentioning at https://github.com/rusefi/rusefi/wiki/HOWTO-M73-v12-on-Proteus#black-23-pin-776228-1-on-black-proteus-02 and more current new 23 pinout like https://github.com/rusefi/rusefi/wiki/HOWTO-M73-v12-on-Proteus#black-23-pin-776228-1-on-green-proteus-03)

![image](https://user-images.githubusercontent.com/48498823/135319641-cd752aef-3390-4ab4-b449-0c63364907de.png)

**Comment by rusefillc** [comment]
Let's double-check whole connector?

I assume this was copy-pasted into all boards, let's NOT fix now in other boards to reduce chance of conflicts with data entry

**Comment by Qwerty-OFF** [comment]
Fixed, please check

**Comment by rusefillc** [comment]
@mck1117 says it's https://rusefi.com/docs/pinouts/proteus/ which is wrong

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/issues/3291

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/135566085-1ba14f5c-59b1-41b4-8296-c0a6caa8958f.png)

**Comment by Qwerty-OFF** [comment]
Fixed
![image](https://user-images.githubusercontent.com/4116383/135641573-8fda619c-6f3a-42de-ae0f-0f71f080a1ad.png)
![image](https://user-images.githubusercontent.com/4116383/135641611-49b8fda0-78db-427e-8d08-6dea2551ba4d.png)
