### ISSUE TITLE
Account for unpopulated Proteus fly-back diodes

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-K-125-adapter#12]
two of Proteus four fly-back diodes are never populated since JLC and single side assembly

the best way for us is to have our own fly backs if we use those two channels and a text note on the schematics that Proteus potentially has second diode while usually it does not

See https://github.com/mck1117/proteus/issues/104

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/135723210-9d16d03a-26d3-4a8d-962d-b3bd372b075d.png)

**Comment by rusefillc** [comment]
love it :)
