### ISSUE TITLE
VTEC and VTC seem to be high-side solenoids

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-K-125-adapter#13]
open question what current do we need and what current does Proteus support here

Do we need any fly-back here?

![image](https://user-images.githubusercontent.com/48498823/135719557-9117d83a-eb97-4c23-ae5a-44165d2bc05d.png)

**Comment by rusefillc** [comment]
@mck1117 @blundar ^^^

**Comment by mck1117** [comment]
VTEC is just on/off (no PWM), so no flyback diode needed.  The high side outputs on Proteus should be able to handle vtec no problem.

**Comment by Qwerty-OFF** [comment]
Done
![image](https://user-images.githubusercontent.com/4116383/135731145-a423782e-2957-41f2-81f7-76005ef9cf09.png)
![image](https://user-images.githubusercontent.com/4116383/135731148-bd4e7444-39ae-4230-82b5-df4fd6640bbf.png)

**Comment by blundar** [comment]
I'd be a little more cautious with VTC than Vtec.  You'll need to run a
variable PWM signal to VTC so flyback might be a little bit more of an
issue.
-D

**Comment by rusefillc** [comment]
let's add flyback for VTC and DNP flyback footprint for Vtec just to be safe

**Comment by blundar** [comment]
Vtec solenoid has a flyback diode on OEM ECU.  Typically 0.8-1.2A draw.
Not a very angry solenoid.
-D

**Comment by rusefillc** [comment]
let's add flyback for both VTC and VTEC based on what @blundar says

**Comment by mck1117** [comment]
No - you actually don't want flyback on VTEC.  VTEC is on-off, which means you want it to turn off quickly, which means no flyback.

**Comment by blundar** [comment]
I'm just relaying what OEM driver circuitry looks like...  They have a
1N4001 flyback diode on OBD1 and what looks like a SOD123 package on a
accord K ECU.  It's not SMA big, it's not SOD323 small.

**Comment by blundar** [comment]
The OEM ECU code also has timer code to delay transitions from non-vtec to
vtec fuel/ign, assuming certain delays in activation + deactivation.  It's
been 10+ years since I was wafting in that assembly but I distinctly
remember asymmetric delays.

**Comment by Qwerty-OFF** [comment]
Added DNP flyback footprint
![image](https://user-images.githubusercontent.com/4116383/135770384-691264a8-a0aa-4f43-bc92-fc7cc67443d1.png)

**Comment by rusefillc** [comment]
VTC should definitely be populated

**Comment by Qwerty-OFF** [comment]
Fixed
