### ISSUE TITLE
What kind of IAC is that?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-K-125-adapter#14]
this IAC is what? idle air control? why does it have three wires GND +12v and ECU? what is the ECU wire?

![image](https://user-images.githubusercontent.com/48498823/135719874-f4ee5ea5-5ebf-4976-b990-daf9d7d60011.png)

**Comment by rusefillc** [comment]
https://www.k20a.org/threads/iacv-pinouts.98463/ says low side, inductive load.. why 3rd wire?!

**Comment by blundar** [comment]
https://www.aemelectronics.com/files/instructions/30-6030%20Series%202%20Plug%20&%20Play%20EMS.pdf

AEM list it as using PW1, which is typically low side.

https://www.aemelectronics.com/sites/default/files/aem_product_instructions/30-3502_01-05_Honda_K_Series_PnP_Harness_Instructions.pdf

AEM lists it as " Lowside switch, 4A max with internal f ly back diode.
Inductiv e load should NOT have full time power"

Really not sure why the ground is there .
-Dave

**Comment by rusefillc** [comment]
Let's wire as "normal" low side solenoid with a jumper just in case

**Comment by Qwerty-OFF** [comment]
With a flyback diode?

**Comment by rusefillc** [comment]
yes, idle valve solenoids always a flyback.

**Comment by Qwerty-OFF** [comment]
Done
![image](https://user-images.githubusercontent.com/4116383/135770692-060acbd9-2322-48ab-aa83-40597d5c9607.png)
![image](https://user-images.githubusercontent.com/4116383/135770697-fb4bcdeb-4f94-4b08-b5f2-fdacd4d4df56.png)
