### ISSUE TITLE
D15 ETB Relay

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-K-125-adapter#15]
![image](https://user-images.githubusercontent.com/48498823/135720192-391a4a88-71ac-425d-9a85-eae5272eba34.png)

@Qwerty-OFF which vehicle has that? can you please fill in D15 in https://docs.google.com/spreadsheets/d/1G6FDarE99hbd0HSs6bh5kEkZy6p-kYTxa0NcJpE1HUc/ ?

**Comment by Qwerty-OFF** [comment]
Element 2003, Element 2008, acura TSX 2005
Filled

**Comment by rusefillc** [comment]
Let's wire in default configuration looks like a useful wire

looks like low-side?

**Comment by Qwerty-OFF** [comment]
Done
![image](https://user-images.githubusercontent.com/4116383/135731159-39ff6882-ecc1-4e0f-a800-d9668b21b25e.png)
