### ISSUE TITLE
Charging system

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-K-125-adapter#16]
What wires are those do we care?

![image](https://user-images.githubusercontent.com/48498823/135720555-4adeef0b-4ec8-411e-85c4-db3cbc40176b.png)

**Comment by rusefillc** [comment]
https://www.k20a.org/threads/which-is-the-field-wire-on-a-k-series-alternator.73114/

https://www.hondata.com/forum/viewtopic.php?t=5383

B10 is definitely charging light on the dash let's do low side control with a via/jumper just in case

**Comment by rusefillc** [comment]
B13 alternator control? let's wire to high side with a jumper just in case?

**Comment by rusefillc** [comment]
and B18 let's leave as is that looks to be feedback from alternator

**Comment by Qwerty-OFF** [comment]
Done
![image](https://user-images.githubusercontent.com/4116383/135731223-7cec942b-e90a-4f1c-8a7b-3709c7ae6ccd.png)
