### ISSUE TITLE
WBO: please make connector more self-contained

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-K-125-adapter#17]
current 8 pin WBO headers is requiring extra wiring outside of the 8 pin right?

let's have a more full 10 pin connector

if 90 degree angled version is available let's place 90 degree angled version not far from the edge facing the edge. maybe 3cm away from board edge?

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/135770070-94e4f24e-8e91-464b-9bc2-c773b41c1361.png)
