### ISSUE TITLE
connectors silk

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-K-125-adapter#18]
![image](https://user-images.githubusercontent.com/48498823/135735916-f5004905-0493-44e2-82f8-6906fac0a6a1.png)

let's replace with white/black/black with "inputs / (nothing in the middle) / outputs"

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/135769128-f0d3f3ad-710c-4604-ae97-1bc60d0290b1.png)
