### ISSUE TITLE
Pinout table needs better pin names

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-K-125-adapter#4]
https://docs.google.com/spreadsheets/d/1G6FDarE99hbd0HSs6bh5kEkZy6p-kYTxa0NcJpE1HUc has horrible abbreviations not human-readable pin info

https://docs.google.com/spreadsheets/d/1G6FDarE99hbd0HSs6bh5kEkZy6p-kYTxa0NcJpE1HUc has links to wiring drawings

At the moment we mostly care about 2003 Honda Element since that's the first test mule

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc sorry i have missed this, do you still need my support?
