### ISSUE TITLE
Baro sensor

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-K-125-adapter#7]
Can we check JLC for pressure sensors one more time? If nothing we need an easy to hand solder footprint

**Comment by Qwerty-OFF** [comment]
JLC has resistive sensors like this 
![image](https://user-images.githubusercontent.com/4116383/135358676-7882a204-87f2-4b02-8b6b-a991275be9f4.png)
MPS-3117-006GC-A3_C242002
Can we use it with proteus?
There are also a small number of sensors with i2c bus, but I see no way to connect them to proteus.

**Comment by rusefillc** [comment]
Analog Temp 3 and Analog Temp 4 are usually unused (AT1 and AT2 are CLT and IAT), I believe 2.7K or something under 5K pull-up on those

**Comment by rusefillc** [comment]
@mck1117 says "those sensors are all gauge pressure
aka useless for baro
must be absolute"

non-jlc option would be https://github.com/rusefi/rusefi/tree/master/hardware/Map_MPX footprint

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/135511594-65d23cdb-b696-4a5b-84a1-2f285394b087.png)
Done
