### ISSUE TITLE
Proteus connectors layout

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-K-125-adapter#8]
@mck1117 says "those connectors are backwards. please keep orientation same as real proteus"

which raises the question: on this board do we have space to lay connectors _exactly_ like on Proteus to allow soldering proteus without connectors like a shield?

like https://rusefi.com/forum/viewtopic.php?p=42098#p42098
like https://rusefi.com/forum/viewtopic.php?f=4&t=1701 which is https://github.com/CrazyStriker/hw_PnProteus_72P_NB2

**Comment by rusefillc** [comment]
Speaking of Proteus connector layout can we please also copy-paste the nice proteus connector silk?

![image](https://user-images.githubusercontent.com/48498823/135359968-4f731fd1-ca29-4957-b595-b25699f67e15.png)

**Comment by Qwerty-OFF** [comment]
I made the Proteus component. Do we use it in this board, or do we leave everything as it is?
![image](https://user-images.githubusercontent.com/4116383/135365023-0ac97db6-7f60-4ab1-be6d-313082b3a084.png)
![image](https://user-images.githubusercontent.com/4116383/135365373-d3cec7aa-273f-4356-8e3d-574f895ada5d.png)

**Comment by rusefillc** [comment]
one of the options i am considering is a 35 pin harness patch cord, one side other side black. that case we use two of same patch cords

this would invert "black" and "white" on the adapter

can we go with "power" and "analog" terms instead of "black" and "white" on the adapter?

**Comment by rusefillc** [comment]
@mck1117 FYI ^^^

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/135511982-4827fe09-bdbe-41f5-93eb-971069ae0a3f.png)
Used proteus-compatible footprint
